Resources: 
  deckstable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "decks"
      AttributeDefinitions: 
        - AttributeName: "deckname"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema: 
        - AttributeName: "deckname"
          KeyType: "HASH"
      OnDemandThroughput: 
        MaxReadRequestUnits: "1"
        MaxWriteRequestUnits: "1"
      TableClass: "STANDARD"
  setstable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "sets"
      AttributeDefinitions: 
        - AttributeName: "setname"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema: 
        - AttributeName: "setname"
          KeyType: "HASH"
      OnDemandThroughput: 
        MaxReadRequestUnits: "1"
        MaxWriteRequestUnits: "1"
      TableClass: "STANDARD"
