Resources: 
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: "deckname"
          AttributeType: "S"
        - AttributeName: "lastpricecheckdate"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema: 
        - AttributeName: "deckname"
          KeyType: "HASH"
        - AttributeName: "lastpricecheckdate"
          KeyType: "RANGE"
      OnDemandThroughput: 
        MaxReadRequestUnits: "1"
        MaxWriteRequestUnits: "1"
      TableClass: "STANDARD"
      TableName: "decks"
